# ── Server ──────────────────────────────────────────────────────────────────
server.port=8080

# ── Supabase / PostgreSQL ────────────────────────────────────────────────────
spring.datasource.url=${DB_URL}?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──────────────────────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true


# ── Connection Pool (HikariCP) ───────────────────────────────────────────────
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# ── Setta Spring Boot come resource server ───────────────────────────────────────────────
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://flolfdlndkolqhdjomtv.supabase.co/auth/v1
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://flolfdlndkolqhdjomtv.supabase.co/auth/v1/.well-known/jwks.json